/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        gson = createGson()
            .registerTypeAdapter(Date.class, dateTypeAdapter)
            .registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter)
            .registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter)
            .registerTypeAdapter(LocalDate.class, localDateTypeAdapter)
            .registerTypeAdapter(byte[].class, byteArrayAdapter)
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ACHRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.AccountInfo.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Address.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.AddressExtended.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Amount.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ApplicationInfo.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.BrowserInfo.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CartRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CartResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CheckoutOrder.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CommonField.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Company.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CreateWebsiteCustomerRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Customer.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CustomerAttribute.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CustomerContactInfo.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CustomerContactInfoCommunicationTag.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CustomerDocument.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CustomerPhone.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CustomerPhoneRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CustomerPricingLevel.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.CustomerUPSAddress.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.DeviceRenderOptions.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Event.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ExternalPlatform.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.FeeItem.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ForexQuote.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.GroupInfo.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Installments.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Invoice.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.InvoiceDetail.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.LineItem.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Mandate.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.MerchantDevice.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.MerchantRiskIndicator.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.MiscEvent.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Name.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Note.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OIShowSpecialSituation.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Order.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderCompleteRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderCompleteResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderCustomerRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderItem.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderItemComp.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderItemDetail.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderItemDetailPriceRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderItemPriceRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderItemPriceResponse.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderItemTax.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.OrderTicketDeliveryRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.PaperCheckRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Payment.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.PaymentAch.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.PaymentAppliedDetail.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.PaymentCreditCard.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.PaymentGiftCard.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.PaymentGiftCardRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.PaymentMethodDetails.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.PaymentRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.PaymentsRequest.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Receipt.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ReceiptDetail.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.RiskData.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SDKEphemPubKey.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Schedule.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SeatingProfile.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SeatingProfileDetail.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SeatingTemplate.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SeatingTemplateSection.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SeatingTemplateSectionSeat.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ShopperInteractionDevice.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ShowBudget.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ShowOverflowSeat.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ShowScheduleSeat.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ShowTrackingDetail.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Special.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SpecialAssociatedEvent.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SpecialDetail.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SpecialSituationDefinition.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SpecialType.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.Split.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.SplitAmount.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ThreeDS2RequestData.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.ThreeDSecureData.CustomTypeAdapterFactory())
            .registerTypeAdapterFactory(new com.sightsound.sdk.ticketing.model.WatchList.CustomTypeAdapterFactory())
            .create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
