/*
 * Helios
 * Sight & Sound Theatres Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ActivityType
 */
@JsonAdapter(ActivityType.Adapter.class)
public enum ActivityType {
  
  ADD("ADD"),
  
  CHANGE("CHANGE"),
  
  ORDER_ACTIVITY_ADD("ORDER_ACTIVITY_ADD"),
  
  ORDER_ACTIVITY_CHANGE("ORDER_ACTIVITY_CHANGE"),
  
  ORDER_ACTIVITY_CANCEL("ORDER_ACTIVITY_CANCEL"),
  
  ORDER_ITEM_ACTIVITY_SPECIAL_DISCOUNT_REMOVED("ORDER_ITEM_ACTIVITY_SPECIAL_DISCOUNT_REMOVED"),
  
  ORDER_ITEM_ACTIVITY_SPECIAL_DISCOUNT_APPLIED("ORDER_ITEM_ACTIVITY_SPECIAL_DISCOUNT_APPLIED"),
  
  ORDER_ITEM_ACTIVITY_RESERVED("ORDER_ITEM_ACTIVITY_RESERVED"),
  
  ORDER_ITEM_ACTIVITY_COUNT_INCREASED("ORDER_ITEM_ACTIVITY_COUNT_INCREASED"),
  
  ORDER_ITEM_ACTIVITY_COUNT_DECREASED("ORDER_ITEM_ACTIVITY_COUNT_DECREASED"),
  
  ORDER_ITEM_ACTIVITY_AMOUNT_INCREASED("ORDER_ITEM_ACTIVITY_AMOUNT_INCREASED"),
  
  ORDER_ITEM_ACTIVITY_AMOUNT_DECREASED("ORDER_ITEM_ACTIVITY_AMOUNT_DECREASED"),
  
  ORDER_ITEM_ACTIVITY_DESIGNATION_CHANGE("ORDER_ITEM_ACTIVITY_DESIGNATION_CHANGE"),
  
  ORDER_ITEM_ACTIVITY_TRANSFERRED_IN("ORDER_ITEM_ACTIVITY_TRANSFERRED_IN"),
  
  ORDER_ITEM_ACTIVITY_CANCELLED("ORDER_ITEM_ACTIVITY_CANCELLED"),
  
  ORDER_ITEM_ACTIVITY_SPECIAL_SITUATION_MODIFIED("ORDER_ITEM_ACTIVITY_SPECIAL_SITUATION_MODIFIED");

  private String value;

  ActivityType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ActivityType fromValue(String value) {
    for (ActivityType b : ActivityType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<ActivityType> {
    @Override
    public void write(final JsonWriter jsonWriter, final ActivityType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ActivityType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ActivityType.fromValue(value);
    }
  }
}

