/*
 * Helios
 * Sight & Sound Theatres Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.sightsound.sdk.ticketing.JSON;

/**
 * PaymentCreditCard
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-01T17:16:16.028085Z[Etc/UTC]")
public class PaymentCreditCard {
  public static final String SERIALIZED_NAME_FIRST_DIGIT = "firstDigit";
  @SerializedName(SERIALIZED_NAME_FIRST_DIGIT)
  private String firstDigit;

  public static final String SERIALIZED_NAME_PSP_REFERENCE = "pspReference";
  @SerializedName(SERIALIZED_NAME_PSP_REFERENCE)
  private String pspReference;

  public static final String SERIALIZED_NAME_MERCHANT_REFERENCE = "merchantReference";
  @SerializedName(SERIALIZED_NAME_MERCHANT_REFERENCE)
  private String merchantReference;

  public static final String SERIALIZED_NAME_CARD_HOLDER_NAME = "cardHolderName";
  @SerializedName(SERIALIZED_NAME_CARD_HOLDER_NAME)
  private String cardHolderName;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private BigDecimal amount;

  public static final String SERIALIZED_NAME_CARD_SUMMARY = "cardSummary";
  @SerializedName(SERIALIZED_NAME_CARD_SUMMARY)
  private String cardSummary;

  public static final String SERIALIZED_NAME_APPLIED = "applied";
  @SerializedName(SERIALIZED_NAME_APPLIED)
  private Boolean applied;

  public PaymentCreditCard() { 
  }

  public PaymentCreditCard firstDigit(String firstDigit) {
    
    this.firstDigit = firstDigit;
    return this;
  }

   /**
   * Get firstDigit
   * @return firstDigit
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFirstDigit() {
    return firstDigit;
  }


  public void setFirstDigit(String firstDigit) {
    this.firstDigit = firstDigit;
  }


  public PaymentCreditCard pspReference(String pspReference) {
    
    this.pspReference = pspReference;
    return this;
  }

   /**
   * Get pspReference
   * @return pspReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPspReference() {
    return pspReference;
  }


  public void setPspReference(String pspReference) {
    this.pspReference = pspReference;
  }


  public PaymentCreditCard merchantReference(String merchantReference) {
    
    this.merchantReference = merchantReference;
    return this;
  }

   /**
   * Get merchantReference
   * @return merchantReference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMerchantReference() {
    return merchantReference;
  }


  public void setMerchantReference(String merchantReference) {
    this.merchantReference = merchantReference;
  }


  public PaymentCreditCard cardHolderName(String cardHolderName) {
    
    this.cardHolderName = cardHolderName;
    return this;
  }

   /**
   * Get cardHolderName
   * @return cardHolderName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCardHolderName() {
    return cardHolderName;
  }


  public void setCardHolderName(String cardHolderName) {
    this.cardHolderName = cardHolderName;
  }


  public PaymentCreditCard amount(BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getAmount() {
    return amount;
  }


  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }


  public PaymentCreditCard cardSummary(String cardSummary) {
    
    this.cardSummary = cardSummary;
    return this;
  }

   /**
   * Get cardSummary
   * @return cardSummary
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCardSummary() {
    return cardSummary;
  }


  public void setCardSummary(String cardSummary) {
    this.cardSummary = cardSummary;
  }


  public PaymentCreditCard applied(Boolean applied) {
    
    this.applied = applied;
    return this;
  }

   /**
   * Get applied
   * @return applied
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getApplied() {
    return applied;
  }


  public void setApplied(Boolean applied) {
    this.applied = applied;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentCreditCard paymentCreditCard = (PaymentCreditCard) o;
    return Objects.equals(this.firstDigit, paymentCreditCard.firstDigit) &&
        Objects.equals(this.pspReference, paymentCreditCard.pspReference) &&
        Objects.equals(this.merchantReference, paymentCreditCard.merchantReference) &&
        Objects.equals(this.cardHolderName, paymentCreditCard.cardHolderName) &&
        Objects.equals(this.amount, paymentCreditCard.amount) &&
        Objects.equals(this.cardSummary, paymentCreditCard.cardSummary) &&
        Objects.equals(this.applied, paymentCreditCard.applied);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstDigit, pspReference, merchantReference, cardHolderName, amount, cardSummary, applied);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentCreditCard {\n");
    sb.append("    firstDigit: ").append(toIndentedString(firstDigit)).append("\n");
    sb.append("    pspReference: ").append(toIndentedString(pspReference)).append("\n");
    sb.append("    merchantReference: ").append(toIndentedString(merchantReference)).append("\n");
    sb.append("    cardHolderName: ").append(toIndentedString(cardHolderName)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    cardSummary: ").append(toIndentedString(cardSummary)).append("\n");
    sb.append("    applied: ").append(toIndentedString(applied)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("firstDigit");
    openapiFields.add("pspReference");
    openapiFields.add("merchantReference");
    openapiFields.add("cardHolderName");
    openapiFields.add("amount");
    openapiFields.add("cardSummary");
    openapiFields.add("applied");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to PaymentCreditCard
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (PaymentCreditCard.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in PaymentCreditCard is not found in the empty JSON string", PaymentCreditCard.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!PaymentCreditCard.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PaymentCreditCard` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("firstDigit") != null && !jsonObj.get("firstDigit").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `firstDigit` to be a primitive type in the JSON string but got `%s`", jsonObj.get("firstDigit").toString()));
      }
      if (jsonObj.get("pspReference") != null && !jsonObj.get("pspReference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pspReference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pspReference").toString()));
      }
      if (jsonObj.get("merchantReference") != null && !jsonObj.get("merchantReference").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `merchantReference` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merchantReference").toString()));
      }
      if (jsonObj.get("cardHolderName") != null && !jsonObj.get("cardHolderName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cardHolderName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cardHolderName").toString()));
      }
      if (jsonObj.get("cardSummary") != null && !jsonObj.get("cardSummary").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `cardSummary` to be a primitive type in the JSON string but got `%s`", jsonObj.get("cardSummary").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PaymentCreditCard.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PaymentCreditCard' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PaymentCreditCard> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PaymentCreditCard.class));

       return (TypeAdapter<T>) new TypeAdapter<PaymentCreditCard>() {
           @Override
           public void write(JsonWriter out, PaymentCreditCard value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PaymentCreditCard read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PaymentCreditCard given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PaymentCreditCard
  * @throws IOException if the JSON string is invalid with respect to PaymentCreditCard
  */
  public static PaymentCreditCard fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PaymentCreditCard.class);
  }

 /**
  * Convert an instance of PaymentCreditCard to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

