/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets PricingLevel
 */
@JsonAdapter(PricingLevel.Adapter.class)
public enum PricingLevel {
  
  NOLEVEL("NOLEVEL"),
  
  POSTPAY("POSTPAY"),
  
  LEVEL1("LEVEL1"),
  
  LEVEL2("LEVEL2"),
  
  LEVEL3("LEVEL3"),
  
  HOT("HOT"),
  
  RECEPTOR("RECEPTOR"),
  
  RECEPTIVE("RECEPTIVE"),
  
  NOTIER("NOTIER"),
  
  TIER1("TIER1"),
  
  TIER2("TIER2"),
  
  TIER3("TIER3"),
  
  TIER4("TIER4");

  private String value;

  PricingLevel(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static PricingLevel fromValue(String value) {
    for (PricingLevel b : PricingLevel.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<PricingLevel> {
    @Override
    public void write(final JsonWriter jsonWriter, final PricingLevel enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public PricingLevel read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return PricingLevel.fromValue(value);
    }
  }
}

