/*
 * Partner Ticketing API
 * Sight & Sound Theatres Partner Ticketing API
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: DeveloperTeam@sight-sound.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sightsound.sdk.ticketing.model.Invoice;
import com.sightsound.sdk.ticketing.model.InvoiceCompany;
import com.sightsound.sdk.ticketing.model.Receipt;
import com.sightsound.sdk.ticketing.model.ReceiptDetailType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.sightsound.sdk.ticketing.JSON;

/**
 * ReceiptDetail
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-18T19:37:37.998841Z[Etc/UTC]")
public class ReceiptDetail {
  public static final String SERIALIZED_NAME_RECEIPT_NUMBER = "receiptNumber";
  @SerializedName(SERIALIZED_NAME_RECEIPT_NUMBER)
  private Long receiptNumber;

  public static final String SERIALIZED_NAME_SEQ_NUMBER = "seqNumber";
  @SerializedName(SERIALIZED_NAME_SEQ_NUMBER)
  private Integer seqNumber;

  public static final String SERIALIZED_NAME_RECEIPT_COMPANY = "receiptCompany";
  @SerializedName(SERIALIZED_NAME_RECEIPT_COMPANY)
  private InvoiceCompany receiptCompany;

  public static final String SERIALIZED_NAME_RECEIPT_DETAIL_STATUS = "receiptDetailStatus";
  @SerializedName(SERIALIZED_NAME_RECEIPT_DETAIL_STATUS)
  private String receiptDetailStatus;

  public static final String SERIALIZED_NAME_RECEIPT_DETAIL_AMOUNT = "receiptDetailAmount";
  @SerializedName(SERIALIZED_NAME_RECEIPT_DETAIL_AMOUNT)
  private BigDecimal receiptDetailAmount;

  public static final String SERIALIZED_NAME_DATE = "date";
  @SerializedName(SERIALIZED_NAME_DATE)
  private OffsetDateTime date;

  public static final String SERIALIZED_NAME_CREDIT_SEGMENT1 = "creditSegment1";
  @SerializedName(SERIALIZED_NAME_CREDIT_SEGMENT1)
  private String creditSegment1;

  public static final String SERIALIZED_NAME_CREDIT_SEGMENT2 = "creditSegment2";
  @SerializedName(SERIALIZED_NAME_CREDIT_SEGMENT2)
  private String creditSegment2;

  public static final String SERIALIZED_NAME_CREDIT_SEGMENT3 = "creditSegment3";
  @SerializedName(SERIALIZED_NAME_CREDIT_SEGMENT3)
  private String creditSegment3;

  public static final String SERIALIZED_NAME_CREDIT_SEGMENT4 = "creditSegment4";
  @SerializedName(SERIALIZED_NAME_CREDIT_SEGMENT4)
  private String creditSegment4;

  public static final String SERIALIZED_NAME_CREDIT_SEGMENT5 = "creditSegment5";
  @SerializedName(SERIALIZED_NAME_CREDIT_SEGMENT5)
  private String creditSegment5;

  public static final String SERIALIZED_NAME_DEBIT_SEGMENT1 = "debitSegment1";
  @SerializedName(SERIALIZED_NAME_DEBIT_SEGMENT1)
  private String debitSegment1;

  public static final String SERIALIZED_NAME_DEBIT_SEGMENT2 = "debitSegment2";
  @SerializedName(SERIALIZED_NAME_DEBIT_SEGMENT2)
  private String debitSegment2;

  public static final String SERIALIZED_NAME_DEBIT_SEGMENT3 = "debitSegment3";
  @SerializedName(SERIALIZED_NAME_DEBIT_SEGMENT3)
  private String debitSegment3;

  public static final String SERIALIZED_NAME_DEBIT_SEGMENT4 = "debitSegment4";
  @SerializedName(SERIALIZED_NAME_DEBIT_SEGMENT4)
  private String debitSegment4;

  public static final String SERIALIZED_NAME_DEBIT_SEGMENT5 = "debitSegment5";
  @SerializedName(SERIALIZED_NAME_DEBIT_SEGMENT5)
  private String debitSegment5;

  public static final String SERIALIZED_NAME_INVOICE_COMPANY = "invoiceCompany";
  @SerializedName(SERIALIZED_NAME_INVOICE_COMPANY)
  private InvoiceCompany invoiceCompany;

  public static final String SERIALIZED_NAME_INVOICE_NUMBER = "invoiceNumber";
  @SerializedName(SERIALIZED_NAME_INVOICE_NUMBER)
  private Long invoiceNumber;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private ReceiptDetailType type;

  public static final String SERIALIZED_NAME_GLT_NUMBER = "gltNumber";
  @SerializedName(SERIALIZED_NAME_GLT_NUMBER)
  private Integer gltNumber;

  public static final String SERIALIZED_NAME_GLT_COMPANY = "gltCompany";
  @SerializedName(SERIALIZED_NAME_GLT_COMPANY)
  private InvoiceCompany gltCompany;

  public static final String SERIALIZED_NAME_MODIFY_DATE = "modifyDate";
  @SerializedName(SERIALIZED_NAME_MODIFY_DATE)
  private OffsetDateTime modifyDate;

  public static final String SERIALIZED_NAME_RECEIPT = "receipt";
  @SerializedName(SERIALIZED_NAME_RECEIPT)
  private Receipt receipt;

  public static final String SERIALIZED_NAME_INVOICE = "invoice";
  @SerializedName(SERIALIZED_NAME_INVOICE)
  private Invoice invoice;

  public ReceiptDetail() { 
  }

  public ReceiptDetail receiptNumber(Long receiptNumber) {
    
    this.receiptNumber = receiptNumber;
    return this;
  }

   /**
   * Get receiptNumber
   * @return receiptNumber
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Long getReceiptNumber() {
    return receiptNumber;
  }


  public void setReceiptNumber(Long receiptNumber) {
    this.receiptNumber = receiptNumber;
  }


  public ReceiptDetail seqNumber(Integer seqNumber) {
    
    this.seqNumber = seqNumber;
    return this;
  }

   /**
   * Get seqNumber
   * @return seqNumber
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getSeqNumber() {
    return seqNumber;
  }


  public void setSeqNumber(Integer seqNumber) {
    this.seqNumber = seqNumber;
  }


  public ReceiptDetail receiptCompany(InvoiceCompany receiptCompany) {
    
    this.receiptCompany = receiptCompany;
    return this;
  }

   /**
   * Get receiptCompany
   * @return receiptCompany
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InvoiceCompany getReceiptCompany() {
    return receiptCompany;
  }


  public void setReceiptCompany(InvoiceCompany receiptCompany) {
    this.receiptCompany = receiptCompany;
  }


  public ReceiptDetail receiptDetailStatus(String receiptDetailStatus) {
    
    this.receiptDetailStatus = receiptDetailStatus;
    return this;
  }

   /**
   * Get receiptDetailStatus
   * @return receiptDetailStatus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getReceiptDetailStatus() {
    return receiptDetailStatus;
  }


  public void setReceiptDetailStatus(String receiptDetailStatus) {
    this.receiptDetailStatus = receiptDetailStatus;
  }


  public ReceiptDetail receiptDetailAmount(BigDecimal receiptDetailAmount) {
    
    this.receiptDetailAmount = receiptDetailAmount;
    return this;
  }

   /**
   * Get receiptDetailAmount
   * @return receiptDetailAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getReceiptDetailAmount() {
    return receiptDetailAmount;
  }


  public void setReceiptDetailAmount(BigDecimal receiptDetailAmount) {
    this.receiptDetailAmount = receiptDetailAmount;
  }


  public ReceiptDetail date(OffsetDateTime date) {
    
    this.date = date;
    return this;
  }

   /**
   * Get date
   * @return date
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getDate() {
    return date;
  }


  public void setDate(OffsetDateTime date) {
    this.date = date;
  }


  public ReceiptDetail creditSegment1(String creditSegment1) {
    
    this.creditSegment1 = creditSegment1;
    return this;
  }

   /**
   * Get creditSegment1
   * @return creditSegment1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreditSegment1() {
    return creditSegment1;
  }


  public void setCreditSegment1(String creditSegment1) {
    this.creditSegment1 = creditSegment1;
  }


  public ReceiptDetail creditSegment2(String creditSegment2) {
    
    this.creditSegment2 = creditSegment2;
    return this;
  }

   /**
   * Get creditSegment2
   * @return creditSegment2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreditSegment2() {
    return creditSegment2;
  }


  public void setCreditSegment2(String creditSegment2) {
    this.creditSegment2 = creditSegment2;
  }


  public ReceiptDetail creditSegment3(String creditSegment3) {
    
    this.creditSegment3 = creditSegment3;
    return this;
  }

   /**
   * Get creditSegment3
   * @return creditSegment3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreditSegment3() {
    return creditSegment3;
  }


  public void setCreditSegment3(String creditSegment3) {
    this.creditSegment3 = creditSegment3;
  }


  public ReceiptDetail creditSegment4(String creditSegment4) {
    
    this.creditSegment4 = creditSegment4;
    return this;
  }

   /**
   * Get creditSegment4
   * @return creditSegment4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreditSegment4() {
    return creditSegment4;
  }


  public void setCreditSegment4(String creditSegment4) {
    this.creditSegment4 = creditSegment4;
  }


  public ReceiptDetail creditSegment5(String creditSegment5) {
    
    this.creditSegment5 = creditSegment5;
    return this;
  }

   /**
   * Get creditSegment5
   * @return creditSegment5
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreditSegment5() {
    return creditSegment5;
  }


  public void setCreditSegment5(String creditSegment5) {
    this.creditSegment5 = creditSegment5;
  }


  public ReceiptDetail debitSegment1(String debitSegment1) {
    
    this.debitSegment1 = debitSegment1;
    return this;
  }

   /**
   * Get debitSegment1
   * @return debitSegment1
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDebitSegment1() {
    return debitSegment1;
  }


  public void setDebitSegment1(String debitSegment1) {
    this.debitSegment1 = debitSegment1;
  }


  public ReceiptDetail debitSegment2(String debitSegment2) {
    
    this.debitSegment2 = debitSegment2;
    return this;
  }

   /**
   * Get debitSegment2
   * @return debitSegment2
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDebitSegment2() {
    return debitSegment2;
  }


  public void setDebitSegment2(String debitSegment2) {
    this.debitSegment2 = debitSegment2;
  }


  public ReceiptDetail debitSegment3(String debitSegment3) {
    
    this.debitSegment3 = debitSegment3;
    return this;
  }

   /**
   * Get debitSegment3
   * @return debitSegment3
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDebitSegment3() {
    return debitSegment3;
  }


  public void setDebitSegment3(String debitSegment3) {
    this.debitSegment3 = debitSegment3;
  }


  public ReceiptDetail debitSegment4(String debitSegment4) {
    
    this.debitSegment4 = debitSegment4;
    return this;
  }

   /**
   * Get debitSegment4
   * @return debitSegment4
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDebitSegment4() {
    return debitSegment4;
  }


  public void setDebitSegment4(String debitSegment4) {
    this.debitSegment4 = debitSegment4;
  }


  public ReceiptDetail debitSegment5(String debitSegment5) {
    
    this.debitSegment5 = debitSegment5;
    return this;
  }

   /**
   * Get debitSegment5
   * @return debitSegment5
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDebitSegment5() {
    return debitSegment5;
  }


  public void setDebitSegment5(String debitSegment5) {
    this.debitSegment5 = debitSegment5;
  }


  public ReceiptDetail invoiceCompany(InvoiceCompany invoiceCompany) {
    
    this.invoiceCompany = invoiceCompany;
    return this;
  }

   /**
   * Get invoiceCompany
   * @return invoiceCompany
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InvoiceCompany getInvoiceCompany() {
    return invoiceCompany;
  }


  public void setInvoiceCompany(InvoiceCompany invoiceCompany) {
    this.invoiceCompany = invoiceCompany;
  }


  public ReceiptDetail invoiceNumber(Long invoiceNumber) {
    
    this.invoiceNumber = invoiceNumber;
    return this;
  }

   /**
   * Get invoiceNumber
   * @return invoiceNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getInvoiceNumber() {
    return invoiceNumber;
  }


  public void setInvoiceNumber(Long invoiceNumber) {
    this.invoiceNumber = invoiceNumber;
  }


  public ReceiptDetail type(ReceiptDetailType type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ReceiptDetailType getType() {
    return type;
  }


  public void setType(ReceiptDetailType type) {
    this.type = type;
  }


  public ReceiptDetail gltNumber(Integer gltNumber) {
    
    this.gltNumber = gltNumber;
    return this;
  }

   /**
   * Get gltNumber
   * @return gltNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getGltNumber() {
    return gltNumber;
  }


  public void setGltNumber(Integer gltNumber) {
    this.gltNumber = gltNumber;
  }


  public ReceiptDetail gltCompany(InvoiceCompany gltCompany) {
    
    this.gltCompany = gltCompany;
    return this;
  }

   /**
   * Get gltCompany
   * @return gltCompany
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public InvoiceCompany getGltCompany() {
    return gltCompany;
  }


  public void setGltCompany(InvoiceCompany gltCompany) {
    this.gltCompany = gltCompany;
  }


  public ReceiptDetail modifyDate(OffsetDateTime modifyDate) {
    
    this.modifyDate = modifyDate;
    return this;
  }

   /**
   * Get modifyDate
   * @return modifyDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getModifyDate() {
    return modifyDate;
  }


  public void setModifyDate(OffsetDateTime modifyDate) {
    this.modifyDate = modifyDate;
  }


  public ReceiptDetail receipt(Receipt receipt) {
    
    this.receipt = receipt;
    return this;
  }

   /**
   * Get receipt
   * @return receipt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Receipt getReceipt() {
    return receipt;
  }


  public void setReceipt(Receipt receipt) {
    this.receipt = receipt;
  }


  public ReceiptDetail invoice(Invoice invoice) {
    
    this.invoice = invoice;
    return this;
  }

   /**
   * Get invoice
   * @return invoice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Invoice getInvoice() {
    return invoice;
  }


  public void setInvoice(Invoice invoice) {
    this.invoice = invoice;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReceiptDetail receiptDetail = (ReceiptDetail) o;
    return Objects.equals(this.receiptNumber, receiptDetail.receiptNumber) &&
        Objects.equals(this.seqNumber, receiptDetail.seqNumber) &&
        Objects.equals(this.receiptCompany, receiptDetail.receiptCompany) &&
        Objects.equals(this.receiptDetailStatus, receiptDetail.receiptDetailStatus) &&
        Objects.equals(this.receiptDetailAmount, receiptDetail.receiptDetailAmount) &&
        Objects.equals(this.date, receiptDetail.date) &&
        Objects.equals(this.creditSegment1, receiptDetail.creditSegment1) &&
        Objects.equals(this.creditSegment2, receiptDetail.creditSegment2) &&
        Objects.equals(this.creditSegment3, receiptDetail.creditSegment3) &&
        Objects.equals(this.creditSegment4, receiptDetail.creditSegment4) &&
        Objects.equals(this.creditSegment5, receiptDetail.creditSegment5) &&
        Objects.equals(this.debitSegment1, receiptDetail.debitSegment1) &&
        Objects.equals(this.debitSegment2, receiptDetail.debitSegment2) &&
        Objects.equals(this.debitSegment3, receiptDetail.debitSegment3) &&
        Objects.equals(this.debitSegment4, receiptDetail.debitSegment4) &&
        Objects.equals(this.debitSegment5, receiptDetail.debitSegment5) &&
        Objects.equals(this.invoiceCompany, receiptDetail.invoiceCompany) &&
        Objects.equals(this.invoiceNumber, receiptDetail.invoiceNumber) &&
        Objects.equals(this.type, receiptDetail.type) &&
        Objects.equals(this.gltNumber, receiptDetail.gltNumber) &&
        Objects.equals(this.gltCompany, receiptDetail.gltCompany) &&
        Objects.equals(this.modifyDate, receiptDetail.modifyDate) &&
        Objects.equals(this.receipt, receiptDetail.receipt) &&
        Objects.equals(this.invoice, receiptDetail.invoice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(receiptNumber, seqNumber, receiptCompany, receiptDetailStatus, receiptDetailAmount, date, creditSegment1, creditSegment2, creditSegment3, creditSegment4, creditSegment5, debitSegment1, debitSegment2, debitSegment3, debitSegment4, debitSegment5, invoiceCompany, invoiceNumber, type, gltNumber, gltCompany, modifyDate, receipt, invoice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReceiptDetail {\n");
    sb.append("    receiptNumber: ").append(toIndentedString(receiptNumber)).append("\n");
    sb.append("    seqNumber: ").append(toIndentedString(seqNumber)).append("\n");
    sb.append("    receiptCompany: ").append(toIndentedString(receiptCompany)).append("\n");
    sb.append("    receiptDetailStatus: ").append(toIndentedString(receiptDetailStatus)).append("\n");
    sb.append("    receiptDetailAmount: ").append(toIndentedString(receiptDetailAmount)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    creditSegment1: ").append(toIndentedString(creditSegment1)).append("\n");
    sb.append("    creditSegment2: ").append(toIndentedString(creditSegment2)).append("\n");
    sb.append("    creditSegment3: ").append(toIndentedString(creditSegment3)).append("\n");
    sb.append("    creditSegment4: ").append(toIndentedString(creditSegment4)).append("\n");
    sb.append("    creditSegment5: ").append(toIndentedString(creditSegment5)).append("\n");
    sb.append("    debitSegment1: ").append(toIndentedString(debitSegment1)).append("\n");
    sb.append("    debitSegment2: ").append(toIndentedString(debitSegment2)).append("\n");
    sb.append("    debitSegment3: ").append(toIndentedString(debitSegment3)).append("\n");
    sb.append("    debitSegment4: ").append(toIndentedString(debitSegment4)).append("\n");
    sb.append("    debitSegment5: ").append(toIndentedString(debitSegment5)).append("\n");
    sb.append("    invoiceCompany: ").append(toIndentedString(invoiceCompany)).append("\n");
    sb.append("    invoiceNumber: ").append(toIndentedString(invoiceNumber)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    gltNumber: ").append(toIndentedString(gltNumber)).append("\n");
    sb.append("    gltCompany: ").append(toIndentedString(gltCompany)).append("\n");
    sb.append("    modifyDate: ").append(toIndentedString(modifyDate)).append("\n");
    sb.append("    receipt: ").append(toIndentedString(receipt)).append("\n");
    sb.append("    invoice: ").append(toIndentedString(invoice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("receiptNumber");
    openapiFields.add("seqNumber");
    openapiFields.add("receiptCompany");
    openapiFields.add("receiptDetailStatus");
    openapiFields.add("receiptDetailAmount");
    openapiFields.add("date");
    openapiFields.add("creditSegment1");
    openapiFields.add("creditSegment2");
    openapiFields.add("creditSegment3");
    openapiFields.add("creditSegment4");
    openapiFields.add("creditSegment5");
    openapiFields.add("debitSegment1");
    openapiFields.add("debitSegment2");
    openapiFields.add("debitSegment3");
    openapiFields.add("debitSegment4");
    openapiFields.add("debitSegment5");
    openapiFields.add("invoiceCompany");
    openapiFields.add("invoiceNumber");
    openapiFields.add("type");
    openapiFields.add("gltNumber");
    openapiFields.add("gltCompany");
    openapiFields.add("modifyDate");
    openapiFields.add("receipt");
    openapiFields.add("invoice");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("receiptNumber");
    openapiRequiredFields.add("seqNumber");
    openapiRequiredFields.add("date");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ReceiptDetail
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (ReceiptDetail.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in ReceiptDetail is not found in the empty JSON string", ReceiptDetail.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ReceiptDetail.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ReceiptDetail` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ReceiptDetail.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (jsonObj.get("receiptDetailStatus") != null && !jsonObj.get("receiptDetailStatus").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `receiptDetailStatus` to be a primitive type in the JSON string but got `%s`", jsonObj.get("receiptDetailStatus").toString()));
      }
      if (jsonObj.get("creditSegment1") != null && !jsonObj.get("creditSegment1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creditSegment1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creditSegment1").toString()));
      }
      if (jsonObj.get("creditSegment2") != null && !jsonObj.get("creditSegment2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creditSegment2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creditSegment2").toString()));
      }
      if (jsonObj.get("creditSegment3") != null && !jsonObj.get("creditSegment3").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creditSegment3` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creditSegment3").toString()));
      }
      if (jsonObj.get("creditSegment4") != null && !jsonObj.get("creditSegment4").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creditSegment4` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creditSegment4").toString()));
      }
      if (jsonObj.get("creditSegment5") != null && !jsonObj.get("creditSegment5").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `creditSegment5` to be a primitive type in the JSON string but got `%s`", jsonObj.get("creditSegment5").toString()));
      }
      if (jsonObj.get("debitSegment1") != null && !jsonObj.get("debitSegment1").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `debitSegment1` to be a primitive type in the JSON string but got `%s`", jsonObj.get("debitSegment1").toString()));
      }
      if (jsonObj.get("debitSegment2") != null && !jsonObj.get("debitSegment2").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `debitSegment2` to be a primitive type in the JSON string but got `%s`", jsonObj.get("debitSegment2").toString()));
      }
      if (jsonObj.get("debitSegment3") != null && !jsonObj.get("debitSegment3").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `debitSegment3` to be a primitive type in the JSON string but got `%s`", jsonObj.get("debitSegment3").toString()));
      }
      if (jsonObj.get("debitSegment4") != null && !jsonObj.get("debitSegment4").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `debitSegment4` to be a primitive type in the JSON string but got `%s`", jsonObj.get("debitSegment4").toString()));
      }
      if (jsonObj.get("debitSegment5") != null && !jsonObj.get("debitSegment5").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `debitSegment5` to be a primitive type in the JSON string but got `%s`", jsonObj.get("debitSegment5").toString()));
      }
      // validate the optional field `receipt`
      if (jsonObj.getAsJsonObject("receipt") != null) {
        Receipt.validateJsonObject(jsonObj.getAsJsonObject("receipt"));
      }
      // validate the optional field `invoice`
      if (jsonObj.getAsJsonObject("invoice") != null) {
        Invoice.validateJsonObject(jsonObj.getAsJsonObject("invoice"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ReceiptDetail.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ReceiptDetail' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ReceiptDetail> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ReceiptDetail.class));

       return (TypeAdapter<T>) new TypeAdapter<ReceiptDetail>() {
           @Override
           public void write(JsonWriter out, ReceiptDetail value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ReceiptDetail read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ReceiptDetail given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ReceiptDetail
  * @throws IOException if the JSON string is invalid with respect to ReceiptDetail
  */
  public static ReceiptDetail fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ReceiptDetail.class);
  }

 /**
  * Convert an instance of ReceiptDetail to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

