/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AccountInfo
 */
public class AccountInfoTest {
    private final AccountInfo model = new AccountInfo();

    /**
     * Model tests for AccountInfo
     */
    @Test
    public void testAccountInfo() {
        // TODO: test AccountInfo
    }

    /**
     * Test the property 'accountAgeIndicator'
     */
    @Test
    public void accountAgeIndicatorTest() {
        // TODO: test accountAgeIndicator
    }

    /**
     * Test the property 'accountChangeDate'
     */
    @Test
    public void accountChangeDateTest() {
        // TODO: test accountChangeDate
    }

    /**
     * Test the property 'accountChangeIndicator'
     */
    @Test
    public void accountChangeIndicatorTest() {
        // TODO: test accountChangeIndicator
    }

    /**
     * Test the property 'accountCreationDate'
     */
    @Test
    public void accountCreationDateTest() {
        // TODO: test accountCreationDate
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'addCardAttemptsDay'
     */
    @Test
    public void addCardAttemptsDayTest() {
        // TODO: test addCardAttemptsDay
    }

    /**
     * Test the property 'deliveryAddressUsageDate'
     */
    @Test
    public void deliveryAddressUsageDateTest() {
        // TODO: test deliveryAddressUsageDate
    }

    /**
     * Test the property 'deliveryAddressUsageIndicator'
     */
    @Test
    public void deliveryAddressUsageIndicatorTest() {
        // TODO: test deliveryAddressUsageIndicator
    }

    /**
     * Test the property 'homePhone'
     */
    @Test
    public void homePhoneTest() {
        // TODO: test homePhone
    }

    /**
     * Test the property 'mobilePhone'
     */
    @Test
    public void mobilePhoneTest() {
        // TODO: test mobilePhone
    }

    /**
     * Test the property 'passwordChangeDate'
     */
    @Test
    public void passwordChangeDateTest() {
        // TODO: test passwordChangeDate
    }

    /**
     * Test the property 'passwordChangeIndicator'
     */
    @Test
    public void passwordChangeIndicatorTest() {
        // TODO: test passwordChangeIndicator
    }

    /**
     * Test the property 'pastTransactionsDay'
     */
    @Test
    public void pastTransactionsDayTest() {
        // TODO: test pastTransactionsDay
    }

    /**
     * Test the property 'pastTransactionsYear'
     */
    @Test
    public void pastTransactionsYearTest() {
        // TODO: test pastTransactionsYear
    }

    /**
     * Test the property 'paymentAccountAge'
     */
    @Test
    public void paymentAccountAgeTest() {
        // TODO: test paymentAccountAge
    }

    /**
     * Test the property 'paymentAccountIndicator'
     */
    @Test
    public void paymentAccountIndicatorTest() {
        // TODO: test paymentAccountIndicator
    }

    /**
     * Test the property 'purchasesLast6Months'
     */
    @Test
    public void purchasesLast6MonthsTest() {
        // TODO: test purchasesLast6Months
    }

    /**
     * Test the property 'suspiciousActivity'
     */
    @Test
    public void suspiciousActivityTest() {
        // TODO: test suspiciousActivity
    }

    /**
     * Test the property 'workPhone'
     */
    @Test
    public void workPhoneTest() {
        // TODO: test workPhone
    }

}
