/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.OrderItemPriceResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CartResponse
 */
public class CartResponseTest {
    private final CartResponse model = new CartResponse();

    /**
     * Model tests for CartResponse
     */
    @Test
    public void testCartResponse() {
        // TODO: test CartResponse
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'totalPrice'
     */
    @Test
    public void totalPriceTest() {
        // TODO: test totalPrice
    }

    /**
     * Test the property 'taxesFeesPrice'
     */
    @Test
    public void taxesFeesPriceTest() {
        // TODO: test taxesFeesPrice
    }

    /**
     * Test the property 'totalDiscount'
     */
    @Test
    public void totalDiscountTest() {
        // TODO: test totalDiscount
    }

    /**
     * Test the property 'totalSavings'
     */
    @Test
    public void totalSavingsTest() {
        // TODO: test totalSavings
    }

    /**
     * Test the property 'totalTransactionCharge'
     */
    @Test
    public void totalTransactionChargeTest() {
        // TODO: test totalTransactionCharge
    }

    /**
     * Test the property 'totalDueAmount'
     */
    @Test
    public void totalDueAmountTest() {
        // TODO: test totalDueAmount
    }

    /**
     * Test the property 'refundPolicy'
     */
    @Test
    public void refundPolicyTest() {
        // TODO: test refundPolicy
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'ticketBatch'
     */
    @Test
    public void ticketBatchTest() {
        // TODO: test ticketBatch
    }

    /**
     * Test the property 'heldName'
     */
    @Test
    public void heldNameTest() {
        // TODO: test heldName
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'finalSaleDate'
     */
    @Test
    public void finalSaleDateTest() {
        // TODO: test finalSaleDate
    }

    /**
     * Test the property 'tierYear'
     */
    @Test
    public void tierYearTest() {
        // TODO: test tierYear
    }

    /**
     * Test the property 'canTicketsBeMailed'
     */
    @Test
    public void canTicketsBeMailedTest() {
        // TODO: test canTicketsBeMailed
    }

    /**
     * Test the property 'customerNumber'
     */
    @Test
    public void customerNumberTest() {
        // TODO: test customerNumber
    }

    /**
     * Test the property 'postPay'
     */
    @Test
    public void postPayTest() {
        // TODO: test postPay
    }

    /**
     * Test the property 'mustPay'
     */
    @Test
    public void mustPayTest() {
        // TODO: test mustPay
    }

    /**
     * Test the property 'totalPaidAmount'
     */
    @Test
    public void totalPaidAmountTest() {
        // TODO: test totalPaidAmount
    }

    /**
     * Test the property 'groupName'
     */
    @Test
    public void groupNameTest() {
        // TODO: test groupName
    }

    /**
     * Test the property 'refNumber'
     */
    @Test
    public void refNumberTest() {
        // TODO: test refNumber
    }

    /**
     * Test the property 'eticketsAllowed'
     */
    @Test
    public void eticketsAllowedTest() {
        // TODO: test eticketsAllowed
    }

}
