/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Schedule;
import org.openapitools.client.model.ShowBudget;
import org.openapitools.client.model.ShowTrackingDetail;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Event
 */
public class EventTest {
    private final Event model = new Event();

    /**
     * Model tests for Event
     */
    @Test
    public void testEvent() {
        // TODO: test Event
    }

    /**
     * Test the property 'eventCode'
     */
    @Test
    public void eventCodeTest() {
        // TODO: test eventCode
    }

    /**
     * Test the property 'eventName'
     */
    @Test
    public void eventNameTest() {
        // TODO: test eventName
    }

    /**
     * Test the property 'itemType'
     */
    @Test
    public void itemTypeTest() {
        // TODO: test itemType
    }

    /**
     * Test the property 'eventTimeMinutes'
     */
    @Test
    public void eventTimeMinutesTest() {
        // TODO: test eventTimeMinutes
    }

    /**
     * Test the property 'ticketed'
     */
    @Test
    public void ticketedTest() {
        // TODO: test ticketed
    }

    /**
     * Test the property 'ticketStyleCode'
     */
    @Test
    public void ticketStyleCodeTest() {
        // TODO: test ticketStyleCode
    }

    /**
     * Test the property 'locationCode'
     */
    @Test
    public void locationCodeTest() {
        // TODO: test locationCode
    }

    /**
     * Test the property 'seatingTemplateCode'
     */
    @Test
    public void seatingTemplateCodeTest() {
        // TODO: test seatingTemplateCode
    }

    /**
     * Test the property 'eventDisplayColor'
     */
    @Test
    public void eventDisplayColorTest() {
        // TODO: test eventDisplayColor
    }

    /**
     * Test the property 'allowOrderTix'
     */
    @Test
    public void allowOrderTixTest() {
        // TODO: test allowOrderTix
    }

    /**
     * Test the property 'internetSeatsMinimumLimit'
     */
    @Test
    public void internetSeatsMinimumLimitTest() {
        // TODO: test internetSeatsMinimumLimit
    }

    /**
     * Test the property 'eventStartDate'
     */
    @Test
    public void eventStartDateTest() {
        // TODO: test eventStartDate
    }

    /**
     * Test the property 'eventEndDate'
     */
    @Test
    public void eventEndDateTest() {
        // TODO: test eventEndDate
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'eventTypeDetailCode'
     */
    @Test
    public void eventTypeDetailCodeTest() {
        // TODO: test eventTypeDetailCode
    }

    /**
     * Test the property 'compTicketsSeatsMin'
     */
    @Test
    public void compTicketsSeatsMinTest() {
        // TODO: test compTicketsSeatsMin
    }

    /**
     * Test the property 'compTicketsStartDate'
     */
    @Test
    public void compTicketsStartDateTest() {
        // TODO: test compTicketsStartDate
    }

    /**
     * Test the property 'theaterLocation'
     */
    @Test
    public void theaterLocationTest() {
        // TODO: test theaterLocation
    }

    /**
     * Test the property 'empDiscDaysToShow'
     */
    @Test
    public void empDiscDaysToShowTest() {
        // TODO: test empDiscDaysToShow
    }

    /**
     * Test the property 'empDiscPercent'
     */
    @Test
    public void empDiscPercentTest() {
        // TODO: test empDiscPercent
    }

    /**
     * Test the property 'taxCode'
     */
    @Test
    public void taxCodeTest() {
        // TODO: test taxCode
    }

    /**
     * Test the property 'externalBooking'
     */
    @Test
    public void externalBookingTest() {
        // TODO: test externalBooking
    }

    /**
     * Test the property 'externalBookingThreshold'
     */
    @Test
    public void externalBookingThresholdTest() {
        // TODO: test externalBookingThreshold
    }

    /**
     * Test the property 'compTicketsMax'
     */
    @Test
    public void compTicketsMaxTest() {
        // TODO: test compTicketsMax
    }

    /**
     * Test the property 'empDayTicketsMax'
     */
    @Test
    public void empDayTicketsMaxTest() {
        // TODO: test empDayTicketsMax
    }

    /**
     * Test the property 'premierShow'
     */
    @Test
    public void premierShowTest() {
        // TODO: test premierShow
    }

    /**
     * Test the property 'taxable'
     */
    @Test
    public void taxableTest() {
        // TODO: test taxable
    }

    /**
     * Test the property 'allowGroup'
     */
    @Test
    public void allowGroupTest() {
        // TODO: test allowGroup
    }

    /**
     * Test the property 'empSeatsMin'
     */
    @Test
    public void empSeatsMinTest() {
        // TODO: test empSeatsMin
    }

    /**
     * Test the property 'empShowMinutes'
     */
    @Test
    public void empShowMinutesTest() {
        // TODO: test empShowMinutes
    }

    /**
     * Test the property 'empShowMinutesSeatsMin'
     */
    @Test
    public void empShowMinutesSeatsMinTest() {
        // TODO: test empShowMinutesSeatsMin
    }

    /**
     * Test the property 'partnerEvent'
     */
    @Test
    public void partnerEventTest() {
        // TODO: test partnerEvent
    }

    /**
     * Test the property 'enTaxCode'
     */
    @Test
    public void enTaxCodeTest() {
        // TODO: test enTaxCode
    }

    /**
     * Test the property 'eventLogoUrl'
     */
    @Test
    public void eventLogoUrlTest() {
        // TODO: test eventLogoUrl
    }

    /**
     * Test the property 'txnCharge'
     */
    @Test
    public void txnChargeTest() {
        // TODO: test txnCharge
    }

    /**
     * Test the property 'allowGroupDisc'
     */
    @Test
    public void allowGroupDiscTest() {
        // TODO: test allowGroupDisc
    }

    /**
     * Test the property 'sortSequence'
     */
    @Test
    public void sortSequenceTest() {
        // TODO: test sortSequence
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    public void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'showTrackingDetails'
     */
    @Test
    public void showTrackingDetailsTest() {
        // TODO: test showTrackingDetails
    }

    /**
     * Test the property 'budget'
     */
    @Test
    public void budgetTest() {
        // TODO: test budget
    }

    /**
     * Test the property 'zonedEventEndDateTime'
     */
    @Test
    public void zonedEventEndDateTimeTest() {
        // TODO: test zonedEventEndDateTime
    }

    /**
     * Test the property 'zonedEventStartDateTime'
     */
    @Test
    public void zonedEventStartDateTimeTest() {
        // TODO: test zonedEventStartDateTime
    }

}
