/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MiscEvent
 */
public class MiscEventTest {
    private final MiscEvent model = new MiscEvent();

    /**
     * Model tests for MiscEvent
     */
    @Test
    public void testMiscEvent() {
        // TODO: test MiscEvent
    }

    /**
     * Test the property 'eventCode'
     */
    @Test
    public void eventCodeTest() {
        // TODO: test eventCode
    }

    /**
     * Test the property 'itemType'
     */
    @Test
    public void itemTypeTest() {
        // TODO: test itemType
    }

    /**
     * Test the property 'eventDescription'
     */
    @Test
    public void eventDescriptionTest() {
        // TODO: test eventDescription
    }

    /**
     * Test the property 'effectiveStartDate'
     */
    @Test
    public void effectiveStartDateTest() {
        // TODO: test effectiveStartDate
    }

    /**
     * Test the property 'effectiveEndDate'
     */
    @Test
    public void effectiveEndDateTest() {
        // TODO: test effectiveEndDate
    }

    /**
     * Test the property 'showStartDate'
     */
    @Test
    public void showStartDateTest() {
        // TODO: test showStartDate
    }

    /**
     * Test the property 'showEndDate'
     */
    @Test
    public void showEndDateTest() {
        // TODO: test showEndDate
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

}
