/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.Customer;
import org.openapitools.client.model.Order;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Note
 */
public class NoteTest {
    private final Note model = new Note();

    /**
     * Model tests for Note
     */
    @Test
    public void testNote() {
        // TODO: test Note
    }

    /**
     * Test the property 'noteId'
     */
    @Test
    public void noteIdTest() {
        // TODO: test noteId
    }

    /**
     * Test the property 'noteType'
     */
    @Test
    public void noteTypeTest() {
        // TODO: test noteType
    }

    /**
     * Test the property 'noteDate'
     */
    @Test
    public void noteDateTest() {
        // TODO: test noteDate
    }

    /**
     * Test the property 'agent'
     */
    @Test
    public void agentTest() {
        // TODO: test agent
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'customerNumber'
     */
    @Test
    public void customerNumberTest() {
        // TODO: test customerNumber
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'eventCode'
     */
    @Test
    public void eventCodeTest() {
        // TODO: test eventCode
    }

    /**
     * Test the property 'itemNumber'
     */
    @Test
    public void itemNumberTest() {
        // TODO: test itemNumber
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'deleteUserId'
     */
    @Test
    public void deleteUserIdTest() {
        // TODO: test deleteUserId
    }

    /**
     * Test the property 'deleteDate'
     */
    @Test
    public void deleteDateTest() {
        // TODO: test deleteDate
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

}
