/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.openapitools.client.model.OrderItem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrderItemTax
 */
public class OrderItemTaxTest {
    private final OrderItemTax model = new OrderItemTax();

    /**
     * Model tests for OrderItemTax
     */
    @Test
    public void testOrderItemTax() {
        // TODO: test OrderItemTax
    }

    /**
     * Test the property 'orderItem'
     */
    @Test
    public void orderItemTest() {
        // TODO: test orderItem
    }

    /**
     * Test the property 'taxType'
     */
    @Test
    public void taxTypeTest() {
        // TODO: test taxType
    }

    /**
     * Test the property 'jurisdiction'
     */
    @Test
    public void jurisdictionTest() {
        // TODO: test jurisdiction
    }

    /**
     * Test the property 'taxDescription'
     */
    @Test
    public void taxDescriptionTest() {
        // TODO: test taxDescription
    }

    /**
     * Test the property 'taxPercent'
     */
    @Test
    public void taxPercentTest() {
        // TODO: test taxPercent
    }

    /**
     * Test the property 'taxPercentAmount'
     */
    @Test
    public void taxPercentAmountTest() {
        // TODO: test taxPercentAmount
    }

    /**
     * Test the property 'tax'
     */
    @Test
    public void taxTest() {
        // TODO: test tax
    }

    /**
     * Test the property 'entryDate'
     */
    @Test
    public void entryDateTest() {
        // TODO: test entryDate
    }

}
