/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import org.openapitools.client.model.OrderItem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrderItemComp
 */
public class OrderItemCompTest {
    private final OrderItemComp model = new OrderItemComp();

    /**
     * Model tests for OrderItemComp
     */
    @Test
    public void testOrderItemComp() {
        // TODO: test OrderItemComp
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'itemNumber'
     */
    @Test
    public void itemNumberTest() {
        // TODO: test itemNumber
    }

    /**
     * Test the property 'compNumber'
     */
    @Test
    public void compNumberTest() {
        // TODO: test compNumber
    }

    /**
     * Test the property 'eventCode'
     */
    @Test
    public void eventCodeTest() {
        // TODO: test eventCode
    }

    /**
     * Test the property 'compType'
     */
    @Test
    public void compTypeTest() {
        // TODO: test compType
    }

    /**
     * Test the property 'uniqueCode'
     */
    @Test
    public void uniqueCodeTest() {
        // TODO: test uniqueCode
    }

    /**
     * Test the property 'addUserId'
     */
    @Test
    public void addUserIdTest() {
        // TODO: test addUserId
    }

    /**
     * Test the property 'addDate'
     */
    @Test
    public void addDateTest() {
        // TODO: test addDate
    }

    /**
     * Test the property 'adult'
     */
    @Test
    public void adultTest() {
        // TODO: test adult
    }

    /**
     * Test the property 'teen'
     */
    @Test
    public void teenTest() {
        // TODO: test teen
    }

    /**
     * Test the property 'child'
     */
    @Test
    public void childTest() {
        // TODO: test child
    }

    /**
     * Test the property 'discountPercent'
     */
    @Test
    public void discountPercentTest() {
        // TODO: test discountPercent
    }

    /**
     * Test the property 'discCountMax'
     */
    @Test
    public void discCountMaxTest() {
        // TODO: test discCountMax
    }

    /**
     * Test the property 'orderItem'
     */
    @Test
    public void orderItemTest() {
        // TODO: test orderItem
    }

}
