/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ACHRequest;
import org.openapitools.client.model.PaperCheckRequest;
import org.openapitools.client.model.PaymentAch;
import org.openapitools.client.model.PaymentAppliedDetail;
import org.openapitools.client.model.PaymentCreditCard;
import org.openapitools.client.model.PaymentGiftCard;
import org.openapitools.client.model.PaymentsRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Payment
 */
public class PaymentTest {
    private final Payment model = new Payment();

    /**
     * Model tests for Payment
     */
    @Test
    public void testPayment() {
        // TODO: test Payment
    }

    /**
     * Test the property 'paymentDate'
     */
    @Test
    public void paymentDateTest() {
        // TODO: test paymentDate
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'paymentType'
     */
    @Test
    public void paymentTypeTest() {
        // TODO: test paymentType
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'transSequenceNumber'
     */
    @Test
    public void transSequenceNumberTest() {
        // TODO: test transSequenceNumber
    }

    /**
     * Test the property 'checks'
     */
    @Test
    public void checksTest() {
        // TODO: test checks
    }

    /**
     * Test the property 'achRequest'
     */
    @Test
    public void achRequestTest() {
        // TODO: test achRequest
    }

    /**
     * Test the property 'paymentAch'
     */
    @Test
    public void paymentAchTest() {
        // TODO: test paymentAch
    }

    /**
     * Test the property 'paymentCreditCard'
     */
    @Test
    public void paymentCreditCardTest() {
        // TODO: test paymentCreditCard
    }

    /**
     * Test the property 'adyenPaymentRequest'
     */
    @Test
    public void adyenPaymentRequestTest() {
        // TODO: test adyenPaymentRequest
    }

    /**
     * Test the property 'giftCards'
     */
    @Test
    public void giftCardsTest() {
        // TODO: test giftCards
    }

    /**
     * Test the property 'storeCreditCard'
     */
    @Test
    public void storeCreditCardTest() {
        // TODO: test storeCreditCard
    }

    /**
     * Test the property 'applyMoa'
     */
    @Test
    public void applyMoaTest() {
        // TODO: test applyMoa
    }

    /**
     * Test the property 'paymentAppliedInfo'
     */
    @Test
    public void paymentAppliedInfoTest() {
        // TODO: test paymentAppliedInfo
    }

    /**
     * Test the property 'cashApplied'
     */
    @Test
    public void cashAppliedTest() {
        // TODO: test cashApplied
    }

    /**
     * Test the property 'moaApplied'
     */
    @Test
    public void moaAppliedTest() {
        // TODO: test moaApplied
    }

}
