/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SDKEphemPubKey
 */
public class SDKEphemPubKeyTest {
    private final SDKEphemPubKey model = new SDKEphemPubKey();

    /**
     * Model tests for SDKEphemPubKey
     */
    @Test
    public void testSDKEphemPubKey() {
        // TODO: test SDKEphemPubKey
    }

    /**
     * Test the property 'crv'
     */
    @Test
    public void crvTest() {
        // TODO: test crv
    }

    /**
     * Test the property 'kty'
     */
    @Test
    public void ktyTest() {
        // TODO: test kty
    }

    /**
     * Test the property 'x'
     */
    @Test
    public void xTest() {
        // TODO: test x
    }

    /**
     * Test the property 'y'
     */
    @Test
    public void yTest() {
        // TODO: test y
    }

}
