/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.SeatingProfile;
import org.openapitools.client.model.SeatingTemplateSection;
import org.openapitools.client.model.SeatingTemplateSectionSeat;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SeatingTemplate
 */
public class SeatingTemplateTest {
    private final SeatingTemplate model = new SeatingTemplate();

    /**
     * Model tests for SeatingTemplate
     */
    @Test
    public void testSeatingTemplate() {
        // TODO: test SeatingTemplate
    }

    /**
     * Test the property 'seatingTemplateCode'
     */
    @Test
    public void seatingTemplateCodeTest() {
        // TODO: test seatingTemplateCode
    }

    /**
     * Test the property 'seatingCapacity'
     */
    @Test
    public void seatingCapacityTest() {
        // TODO: test seatingCapacity
    }

    /**
     * Test the property 'seatingTemplateDescription'
     */
    @Test
    public void seatingTemplateDescriptionTest() {
        // TODO: test seatingTemplateDescription
    }

    /**
     * Test the property 'overflow'
     */
    @Test
    public void overflowTest() {
        // TODO: test overflow
    }

    /**
     * Test the property 'locationCode'
     */
    @Test
    public void locationCodeTest() {
        // TODO: test locationCode
    }

    /**
     * Test the property 'masterTemplateYN'
     */
    @Test
    public void masterTemplateYNTest() {
        // TODO: test masterTemplateYN
    }

    /**
     * Test the property 'overflowMax'
     */
    @Test
    public void overflowMaxTest() {
        // TODO: test overflowMax
    }

    /**
     * Test the property 'seatProfileCode'
     */
    @Test
    public void seatProfileCodeTest() {
        // TODO: test seatProfileCode
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'wheelchairCapacity'
     */
    @Test
    public void wheelchairCapacityTest() {
        // TODO: test wheelchairCapacity
    }

    /**
     * Test the property 'sections'
     */
    @Test
    public void sectionsTest() {
        // TODO: test sections
    }

    /**
     * Test the property 'seats'
     */
    @Test
    public void seatsTest() {
        // TODO: test seats
    }

    /**
     * Test the property 'profile'
     */
    @Test
    public void profileTest() {
        // TODO: test profile
    }

    /**
     * Test the property 'xcoordCenter'
     */
    @Test
    public void xcoordCenterTest() {
        // TODO: test xcoordCenter
    }

    /**
     * Test the property 'ycoordBestRow'
     */
    @Test
    public void ycoordBestRowTest() {
        // TODO: test ycoordBestRow
    }

}
