/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.OrderItem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShowOverflowSeat
 */
public class ShowOverflowSeatTest {
    private final ShowOverflowSeat model = new ShowOverflowSeat();

    /**
     * Model tests for ShowOverflowSeat
     */
    @Test
    public void testShowOverflowSeat() {
        // TODO: test ShowOverflowSeat
    }

    /**
     * Test the property 'overflowId'
     */
    @Test
    public void overflowIdTest() {
        // TODO: test overflowId
    }

    /**
     * Test the property 'eventCode'
     */
    @Test
    public void eventCodeTest() {
        // TODO: test eventCode
    }

    /**
     * Test the property 'showDateTime'
     */
    @Test
    public void showDateTimeTest() {
        // TODO: test showDateTime
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'itemNumber'
     */
    @Test
    public void itemNumberTest() {
        // TODO: test itemNumber
    }

    /**
     * Test the property 'ticketText'
     */
    @Test
    public void ticketTextTest() {
        // TODO: test ticketText
    }

    /**
     * Test the property 'seatStatus'
     */
    @Test
    public void seatStatusTest() {
        // TODO: test seatStatus
    }

    /**
     * Test the property 'ticketStatus'
     */
    @Test
    public void ticketStatusTest() {
        // TODO: test ticketStatus
    }

    /**
     * Test the property 'orderItem'
     */
    @Test
    public void orderItemTest() {
        // TODO: test orderItem
    }

}
