/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.openapitools.client.model.Order;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for WatchList
 */
public class WatchListTest {
    private final WatchList model = new WatchList();

    /**
     * Model tests for WatchList
     */
    @Test
    public void testWatchList() {
        // TODO: test WatchList
    }

    /**
     * Test the property 'watchListNumber'
     */
    @Test
    public void watchListNumberTest() {
        // TODO: test watchListNumber
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'deadlineDate'
     */
    @Test
    public void deadlineDateTest() {
        // TODO: test deadlineDate
    }

    /**
     * Test the property 'comments'
     */
    @Test
    public void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'addUserId'
     */
    @Test
    public void addUserIdTest() {
        // TODO: test addUserId
    }

    /**
     * Test the property 'addDate'
     */
    @Test
    public void addDateTest() {
        // TODO: test addDate
    }

    /**
     * Test the property 'active'
     */
    @Test
    public void activeTest() {
        // TODO: test active
    }

    /**
     * Test the property 'deactivateDate'
     */
    @Test
    public void deactivateDateTest() {
        // TODO: test deactivateDate
    }

    /**
     * Test the property 'customerNumber'
     */
    @Test
    public void customerNumberTest() {
        // TODO: test customerNumber
    }

    /**
     * Test the property 'deactivateUserId'
     */
    @Test
    public void deactivateUserIdTest() {
        // TODO: test deactivateUserId
    }

    /**
     * Test the property 'lastModifiedDate'
     */
    @Test
    public void lastModifiedDateTest() {
        // TODO: test lastModifiedDate
    }

    /**
     * Test the property 'assignedToUserId'
     */
    @Test
    public void assignedToUserIdTest() {
        // TODO: test assignedToUserId
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

}
