/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AccountAgeIndicatorEnum
 */
public class AccountAgeIndicatorEnumTest {
    /**
     * Model tests for AccountAgeIndicatorEnum
     */
    @Test
    public void testAccountAgeIndicatorEnum() {
        // TODO: test AccountAgeIndicatorEnum
    }

}
