/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sightsound.sdk.ticketing.model.Order;
import com.sightsound.sdk.ticketing.model.OrderItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for GroupInfo
 */
public class GroupInfoTest {
    private final GroupInfo model = new GroupInfo();

    /**
     * Model tests for GroupInfo
     */
    @Test
    public void testGroupInfo() {
        // TODO: test GroupInfo
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'itemNumber'
     */
    @Test
    public void itemNumberTest() {
        // TODO: test itemNumber
    }

    /**
     * Test the property 'eventCode'
     */
    @Test
    public void eventCodeTest() {
        // TODO: test eventCode
    }

    /**
     * Test the property 'showDateTime'
     */
    @Test
    public void showDateTimeTest() {
        // TODO: test showDateTime
    }

    /**
     * Test the property 'groupNumber'
     */
    @Test
    public void groupNumberTest() {
        // TODO: test groupNumber
    }

    /**
     * Test the property 'groupCount'
     */
    @Test
    public void groupCountTest() {
        // TODO: test groupCount
    }

    /**
     * Test the property 'arrivalDateTime'
     */
    @Test
    public void arrivalDateTimeTest() {
        // TODO: test arrivalDateTime
    }

    /**
     * Test the property 'busSpaces'
     */
    @Test
    public void busSpacesTest() {
        // TODO: test busSpaces
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

    /**
     * Test the property 'orderItem'
     */
    @Test
    public void orderItemTest() {
        // TODO: test orderItem
    }

}
