/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrderItemPriceResponse
 */
public class OrderItemPriceResponseTest {
    private final OrderItemPriceResponse model = new OrderItemPriceResponse();

    /**
     * Model tests for OrderItemPriceResponse
     */
    @Test
    public void testOrderItemPriceResponse() {
        // TODO: test OrderItemPriceResponse
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'orderNumber'
     */
    @Test
    public void orderNumberTest() {
        // TODO: test orderNumber
    }

    /**
     * Test the property 'itemNumber'
     */
    @Test
    public void itemNumberTest() {
        // TODO: test itemNumber
    }

    /**
     * Test the property 'subtotalPrice'
     */
    @Test
    public void subtotalPriceTest() {
        // TODO: test subtotalPrice
    }

    /**
     * Test the property 'totalDiscount'
     */
    @Test
    public void totalDiscountTest() {
        // TODO: test totalDiscount
    }

    /**
     * Test the property 'itemStatus'
     */
    @Test
    public void itemStatusTest() {
        // TODO: test itemStatus
    }

    /**
     * Test the property 'bus'
     */
    @Test
    public void busTest() {
        // TODO: test bus
    }

    /**
     * Test the property 'busCount'
     */
    @Test
    public void busCountTest() {
        // TODO: test busCount
    }

}
