/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sightsound.sdk.ticketing.model.CartRequest;
import com.sightsound.sdk.ticketing.model.OrderTicketDeliveryRequest;
import com.sightsound.sdk.ticketing.model.PaymentRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OrderCompleteRequest
 */
public class OrderCompleteRequestTest {
    private final OrderCompleteRequest model = new OrderCompleteRequest();

    /**
     * Model tests for OrderCompleteRequest
     */
    @Test
    public void testOrderCompleteRequest() {
        // TODO: test OrderCompleteRequest
    }

    /**
     * Test the property 'cart'
     */
    @Test
    public void cartTest() {
        // TODO: test cart
    }

    /**
     * Test the property 'delivery'
     */
    @Test
    public void deliveryTest() {
        // TODO: test delivery
    }

    /**
     * Test the property 'payment'
     */
    @Test
    public void paymentTest() {
        // TODO: test payment
    }

    /**
     * Test the property 'seatLockToken'
     */
    @Test
    public void seatLockTokenTest() {
        // TODO: test seatLockToken
    }

    /**
     * Test the property 'emailList'
     */
    @Test
    public void emailListTest() {
        // TODO: test emailList
    }

    /**
     * Test the property 'sameGroupConfirm'
     */
    @Test
    public void sameGroupConfirmTest() {
        // TODO: test sameGroupConfirm
    }

}
