/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sightsound.sdk.ticketing.model.ACHRequest;
import com.sightsound.sdk.ticketing.model.PaperCheckRequest;
import com.sightsound.sdk.ticketing.model.PaymentGiftCardRequest;
import com.sightsound.sdk.ticketing.model.PaymentsRequest;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for PaymentRequest
 */
public class PaymentRequestTest {
    private final PaymentRequest model = new PaymentRequest();

    /**
     * Model tests for PaymentRequest
     */
    @Test
    public void testPaymentRequest() {
        // TODO: test PaymentRequest
    }

    /**
     * Test the property 'paymentType'
     */
    @Test
    public void paymentTypeTest() {
        // TODO: test paymentType
    }

    /**
     * Test the property 'checks'
     */
    @Test
    public void checksTest() {
        // TODO: test checks
    }

    /**
     * Test the property 'achRequest'
     */
    @Test
    public void achRequestTest() {
        // TODO: test achRequest
    }

    /**
     * Test the property 'adyenPaymentRequest'
     */
    @Test
    public void adyenPaymentRequestTest() {
        // TODO: test adyenPaymentRequest
    }

    /**
     * Test the property 'giftCards'
     */
    @Test
    public void giftCardsTest() {
        // TODO: test giftCards
    }

    /**
     * Test the property 'storeCreditCard'
     */
    @Test
    public void storeCreditCardTest() {
        // TODO: test storeCreditCard
    }

    /**
     * Test the property 'applyMoa'
     */
    @Test
    public void applyMoaTest() {
        // TODO: test applyMoa
    }

}
