/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sightsound.sdk.ticketing.model.Customer;
import com.sightsound.sdk.ticketing.model.ReceiptDetail;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Receipt
 */
public class ReceiptTest {
    private final Receipt model = new Receipt();

    /**
     * Model tests for Receipt
     */
    @Test
    public void testReceipt() {
        // TODO: test Receipt
    }

    /**
     * Test the property 'receiptNumber'
     */
    @Test
    public void receiptNumberTest() {
        // TODO: test receiptNumber
    }

    /**
     * Test the property 'company'
     */
    @Test
    public void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'checkNumber'
     */
    @Test
    public void checkNumberTest() {
        // TODO: test checkNumber
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'receiptDate'
     */
    @Test
    public void receiptDateTest() {
        // TODO: test receiptDate
    }

    /**
     * Test the property 'customerNumber'
     */
    @Test
    public void customerNumberTest() {
        // TODO: test customerNumber
    }

    /**
     * Test the property 'receiptAmount'
     */
    @Test
    public void receiptAmountTest() {
        // TODO: test receiptAmount
    }

    /**
     * Test the property 'receiptStatus'
     */
    @Test
    public void receiptStatusTest() {
        // TODO: test receiptStatus
    }

    /**
     * Test the property 'paidAmount'
     */
    @Test
    public void paidAmountTest() {
        // TODO: test paidAmount
    }

    /**
     * Test the property 'glPeriod'
     */
    @Test
    public void glPeriodTest() {
        // TODO: test glPeriod
    }

    /**
     * Test the property 'bankCode'
     */
    @Test
    public void bankCodeTest() {
        // TODO: test bankCode
    }

    /**
     * Test the property 'paymentType'
     */
    @Test
    public void paymentTypeTest() {
        // TODO: test paymentType
    }

    /**
     * Test the property 'receiptType'
     */
    @Test
    public void receiptTypeTest() {
        // TODO: test receiptType
    }

    /**
     * Test the property 'controlNumber'
     */
    @Test
    public void controlNumberTest() {
        // TODO: test controlNumber
    }

    /**
     * Test the property 'reasonCode'
     */
    @Test
    public void reasonCodeTest() {
        // TODO: test reasonCode
    }

    /**
     * Test the property 'baseAmount'
     */
    @Test
    public void baseAmountTest() {
        // TODO: test baseAmount
    }

    /**
     * Test the property 'location'
     */
    @Test
    public void locationTest() {
        // TODO: test location
    }

    /**
     * Test the property 'ccSeqNumber'
     */
    @Test
    public void ccSeqNumberTest() {
        // TODO: test ccSeqNumber
    }

    /**
     * Test the property 'modifyDate'
     */
    @Test
    public void modifyDateTest() {
        // TODO: test modifyDate
    }

    /**
     * Test the property 'executiveSeriesReceiptNumber'
     */
    @Test
    public void executiveSeriesReceiptNumberTest() {
        // TODO: test executiveSeriesReceiptNumber
    }

    /**
     * Test the property 'syncSource'
     */
    @Test
    public void syncSourceTest() {
        // TODO: test syncSource
    }

    /**
     * Test the property 'addUserId'
     */
    @Test
    public void addUserIdTest() {
        // TODO: test addUserId
    }

    /**
     * Test the property 'editUserId'
     */
    @Test
    public void editUserIdTest() {
        // TODO: test editUserId
    }

    /**
     * Test the property 'receiptDetails'
     */
    @Test
    public void receiptDetailsTest() {
        // TODO: test receiptDetails
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

}
