/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SpecialSituationDefinition
 */
public class SpecialSituationDefinitionTest {
    private final SpecialSituationDefinition model = new SpecialSituationDefinition();

    /**
     * Model tests for SpecialSituationDefinition
     */
    @Test
    public void testSpecialSituationDefinition() {
        // TODO: test SpecialSituationDefinition
    }

    /**
     * Test the property 'specialSituationCode'
     */
    @Test
    public void specialSituationCodeTest() {
        // TODO: test specialSituationCode
    }

    /**
     * Test the property 'display'
     */
    @Test
    public void displayTest() {
        // TODO: test display
    }

    /**
     * Test the property 'emailDestination'
     */
    @Test
    public void emailDestinationTest() {
        // TODO: test emailDestination
    }

    /**
     * Test the property 'itemTypeCode'
     */
    @Test
    public void itemTypeCodeTest() {
        // TODO: test itemTypeCode
    }

    /**
     * Test the property 'sendEmail'
     */
    @Test
    public void sendEmailTest() {
        // TODO: test sendEmail
    }

    /**
     * Test the property 'sortOrder'
     */
    @Test
    public void sortOrderTest() {
        // TODO: test sortOrder
    }

    /**
     * Test the property 'specialSituationDesc'
     */
    @Test
    public void specialSituationDescTest() {
        // TODO: test specialSituationDesc
    }

}
