/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.sightsound.sdk.ticketing.model.DeviceRenderOptions;
import com.sightsound.sdk.ticketing.model.SDKEphemPubKey;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ThreeDS2RequestData
 */
public class ThreeDS2RequestDataTest {
    private final ThreeDS2RequestData model = new ThreeDS2RequestData();

    /**
     * Model tests for ThreeDS2RequestData
     */
    @Test
    public void testThreeDS2RequestData() {
        // TODO: test ThreeDS2RequestData
    }

    /**
     * Test the property 'authenticationOnly'
     */
    @Test
    public void authenticationOnlyTest() {
        // TODO: test authenticationOnly
    }

    /**
     * Test the property 'challengeIndicator'
     */
    @Test
    public void challengeIndicatorTest() {
        // TODO: test challengeIndicator
    }

    /**
     * Test the property 'deviceChannel'
     */
    @Test
    public void deviceChannelTest() {
        // TODO: test deviceChannel
    }

    /**
     * Test the property 'deviceRenderOptions'
     */
    @Test
    public void deviceRenderOptionsTest() {
        // TODO: test deviceRenderOptions
    }

    /**
     * Test the property 'notificationURL'
     */
    @Test
    public void notificationURLTest() {
        // TODO: test notificationURL
    }

    /**
     * Test the property 'sdkAppID'
     */
    @Test
    public void sdkAppIDTest() {
        // TODO: test sdkAppID
    }

    /**
     * Test the property 'sdkEncData'
     */
    @Test
    public void sdkEncDataTest() {
        // TODO: test sdkEncData
    }

    /**
     * Test the property 'sdkEphemPubKey'
     */
    @Test
    public void sdkEphemPubKeyTest() {
        // TODO: test sdkEphemPubKey
    }

    /**
     * Test the property 'sdkMaxTimeout'
     */
    @Test
    public void sdkMaxTimeoutTest() {
        // TODO: test sdkMaxTimeout
    }

    /**
     * Test the property 'sdkReferenceNumber'
     */
    @Test
    public void sdkReferenceNumberTest() {
        // TODO: test sdkReferenceNumber
    }

    /**
     * Test the property 'sdkTransID'
     */
    @Test
    public void sdkTransIDTest() {
        // TODO: test sdkTransID
    }

    /**
     * Test the property 'threeDSCompInd'
     */
    @Test
    public void threeDSCompIndTest() {
        // TODO: test threeDSCompInd
    }

    /**
     * Test the property 'threeDSRequestorURL'
     */
    @Test
    public void threeDSRequestorURLTest() {
        // TODO: test threeDSRequestorURL
    }

    /**
     * Test the property 'threeDSServerTransID'
     */
    @Test
    public void threeDSServerTransIDTest() {
        // TODO: test threeDSServerTransID
    }

    /**
     * Test the property 'messageVersion'
     */
    @Test
    public void messageVersionTest() {
        // TODO: test messageVersion
    }

    /**
     * Test the property 'threeDSRequestorID'
     */
    @Test
    public void threeDSRequestorIDTest() {
        // TODO: test threeDSRequestorID
    }

    /**
     * Test the property 'threeDSRequestorChallengeInd'
     */
    @Test
    public void threeDSRequestorChallengeIndTest() {
        // TODO: test threeDSRequestorChallengeInd
    }

    /**
     * Test the property 'threeDSRequestorName'
     */
    @Test
    public void threeDSRequestorNameTest() {
        // TODO: test threeDSRequestorName
    }

    /**
     * Test the property 'acquirerBIN'
     */
    @Test
    public void acquirerBINTest() {
        // TODO: test acquirerBIN
    }

    /**
     * Test the property 'acquirerMerchantID'
     */
    @Test
    public void acquirerMerchantIDTest() {
        // TODO: test acquirerMerchantID
    }

    /**
     * Test the property 'mcc'
     */
    @Test
    public void mccTest() {
        // TODO: test mcc
    }

    /**
     * Test the property 'merchantName'
     */
    @Test
    public void merchantNameTest() {
        // TODO: test merchantName
    }

    /**
     * Test the property 'transactionType'
     */
    @Test
    public void transactionTypeTest() {
        // TODO: test transactionType
    }

    /**
     * Test the property 'whiteListStatus'
     */
    @Test
    public void whiteListStatusTest() {
        // TODO: test whiteListStatus
    }

}
