/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sightsound.sdk.ticketing.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ThreeDSecureData
 */
public class ThreeDSecureDataTest {
    private final ThreeDSecureData model = new ThreeDSecureData();

    /**
     * Model tests for ThreeDSecureData
     */
    @Test
    public void testThreeDSecureData() {
        // TODO: test ThreeDSecureData
    }

    /**
     * Test the property 'authenticationResponse'
     */
    @Test
    public void authenticationResponseTest() {
        // TODO: test authenticationResponse
    }

    /**
     * Test the property 'cavv'
     */
    @Test
    public void cavvTest() {
        // TODO: test cavv
    }

    /**
     * Test the property 'cavvAlgorithm'
     */
    @Test
    public void cavvAlgorithmTest() {
        // TODO: test cavvAlgorithm
    }

    /**
     * Test the property 'directoryResponse'
     */
    @Test
    public void directoryResponseTest() {
        // TODO: test directoryResponse
    }

    /**
     * Test the property 'eci'
     */
    @Test
    public void eciTest() {
        // TODO: test eci
    }

    /**
     * Test the property 'threeDSVersion'
     */
    @Test
    public void threeDSVersionTest() {
        // TODO: test threeDSVersion
    }

    /**
     * Test the property 'xid'
     */
    @Test
    public void xidTest() {
        // TODO: test xid
    }

    /**
     * Test the property 'dsTransID'
     */
    @Test
    public void dsTransIDTest() {
        // TODO: test dsTransID
    }

}
